# GitHub Action for building Libuv
name: dll for Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'What version of libuv to compile and commit to repo?'
        required: true
        default: 1.44.2
        type: number

jobs:
  windows:
    runs-on: windows-${{ matrix.config.server }}
    continue-on-error: true
    name: windows-${{ matrix.config.toolchain}}-${{ matrix.config.arch}}
    env:
      VERSION: ${{ github.event.inputs.version }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {toolchain: Visual Studio 16 2019, arch: x64, server: 2019}
    steps:
      - uses: actions/checkout@v3
      - name: Envinfo
        run: npx envinfo
      - name: Build
        shell: cmd
        run: |
          curl -L https://github.com/libuv/libuv/archive/refs/tags/v${{ env.VERSION }}.zip --output libuv.zip
          unzip -xoq libuv.zip
          cd libuv-${{ env.VERSION }}
          mkdir build
          cd build
          cmake .. -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DBUILDING_UV_SHARED=1 -G "${{ matrix.config.toolchain }}" -A ${{ matrix.config.arch }}
          cmake --build . --config Release
          dir Release
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Upload/Commit to Repo
        shell: cmd
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdir lib\Windows\
          copy /Y libuv-${{ env.VERSION }}\build\Release\uv.dll lib\Windows\
          git add lib
          git commit -m "created uv.dll - for Windows x64"
          git push -q
          copy /Y libuv-${{ env.VERSION }}\include\*.* headers\original
          copy /Y libuv-${{ env.VERSION }}\include\uv\*.* headers\original\uv\
          git add headers
          git commit -m "Libuv *.h headers"
          git push -q
