name: "Windows "

on:
  push:
    branches: [ 0.3x ]
  pull_request:
    branches: [ 0.3x ]

jobs:
  multi:
    name: ${{ matrix.operating-system }} CI - PHP ${{ matrix.php-versions }}
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest]
        php-versions: ['7.4', '8.0', '8.1', '8.2']
        include:
          - php-versions: '7.4'
            php-coverage: xdebug
          - php-versions: '8.0'
            php-coverage: none
          - php-versions: '8.1'
            php-coverage: none
          - php-versions: '8.2'
            php-coverage: none
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          extensions: ffi, opcache, fileinfo, mbstring, openssl, simplexml, dom, sockets, sodium
          coverage: ${{ matrix.php-coverage }}
          ini-values: ffi.enable="true", opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=256M
      - name: Install dependencies
        run: |
          composer install
          composer require --dev phpunit/phpunit ~9
      - name: Test with phpunit
        timeout-minutes: 3
        run: vendor/bin/phpunit --coverage-clover clover.xml
      - name: Submit code coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./clover.xml, build/logs/clover.xml # optional
